YALE_RUNTIME_SRC_LIB :=
YALE_RUNTIME_SRC := $(YALE_RUNTIME_SRC_LIB)

YALE_RUNTIME_SRC_LIB := $(patsubst %,$(DIRYALE_RUNTIME)/%,$(YALE_RUNTIME_SRC_LIB))
YALE_RUNTIME_SRC := $(patsubst %,$(DIRYALE_RUNTIME)/%,$(YALE_RUNTIME_SRC))

YALE_RUNTIME_OBJ_LIB := $(patsubst %.c,%.o,$(YALE_RUNTIME_SRC_LIB))
YALE_RUNTIME_OBJ := $(patsubst %.c,%.o,$(YALE_RUNTIME_SRC))

YALE_RUNTIME_DEP_LIB := $(patsubst %.c,%.d,$(YALE_RUNTIME_SRC_LIB))
YALE_RUNTIME_DEP := $(patsubst %.c,%.d,$(YALE_RUNTIME_SRC))

YALE_RUNTIME_ASM_LIB := $(patsubst %.c,%.s,$(YALE_RUNTIME_SRC_LIB))
YALE_RUNTIME_ASM := $(patsubst %.c,%.s,$(YALE_RUNTIME_SRC))

CFLAGS_YALE_RUNTIME := 

MAKEFILES_YALE_RUNTIME := $(DIRYALE_RUNTIME)/module.mk
LIBS_YALE_RUNTIME :=

.PHONY: YALE_RUNTIME clean_YALE_RUNTIME distclean_YALE_RUNTIME unit_YALE_RUNTIME $(LCYALE_RUNTIME) clean_$(LCYALE_RUNTIME) distclean_$(LCYALE_RUNTIME) unit_$(LCYALE_RUNTIME)

$(LCYALE_RUNTIME): YALE_RUNTIME
clean_$(LCYALE_RUNTIME): clean_YALE_RUNTIME
distclean_$(LCYALE_RUNTIME): distclean_YALE_RUNTIME
unit_$(LCYALE_RUNTIME): unit_YALE_RUNTIME

YALE_RUNTIME: $(DIRYALE_RUNTIME)/libruntime.a

unit_YALE_RUNTIME: $(MAKEFILES_COMMON) $(MAKEFILES_YALE_RUNTIME)
	@true

$(DIRYALE_RUNTIME)/libruntime.a: $(YALE_RUNTIME_OBJ_LIB) $(MAKEFILES_COMMON) $(MAKEFILES_YALE_RUNTIME)
	rm -f $@
	ar rvs $@ $(filter %.o,$^)

$(YALE_RUNTIME_OBJ): %.o: %.c %.d $(MAKEFILES_COMMON) $(MAKEFILES_YALE_RUNTIME)
	$(CC) $(CFLAGS) -c -o $*.o $*.c $(CFLAGS_YALE_RUNTIME)
	$(CC) $(CFLAGS) -c -S -o $*.s $*.c $(CFLAGS_YALE_RUNTIME)

$(YALE_RUNTIME_DEP): %.d: %.c $(MAKEFILES_COMMON) $(MAKEFILES_YALE_RUNTIME)
	$(CC) $(CFLAGS) -MM -MP -MT "$*.d $*.o" -o $*.d $*.c $(CFLAGS_YALE_RUNTIME)

clean_YALE_RUNTIME:
	rm -f $(YALE_RUNTIME_OBJ) $(YALE_RUNTIME_DEP) $(YALE_RUNTIME_ASM)

distclean_YALE_RUNTIME: clean_YALE_RUNTIME
	rm -f $(DIRYALE_RUNTIME)/libruntime.a

-include $(DIRYALE_RUNTIME)/*.d
