YALE_PYBRIDGE_SRC_LIB :=
YALE_PYBRIDGE_SRC := $(YALE_PYBRIDGE_SRC_LIB) httpcpy.c

YALE_PYBRIDGE_SRC_LIB := $(patsubst %,$(DIRYALE_PYBRIDGE)/%,$(YALE_PYBRIDGE_SRC_LIB))
YALE_PYBRIDGE_SRC := $(patsubst %,$(DIRYALE_PYBRIDGE)/%,$(YALE_PYBRIDGE_SRC))

YALE_PYBRIDGE_OBJ_LIB := $(patsubst %.c,%.o,$(YALE_PYBRIDGE_SRC_LIB))
YALE_PYBRIDGE_OBJ := $(patsubst %.c,%.o,$(YALE_PYBRIDGE_SRC))

YALE_PYBRIDGE_DEP_LIB := $(patsubst %.c,%.d,$(YALE_PYBRIDGE_SRC_LIB))
YALE_PYBRIDGE_DEP := $(patsubst %.c,%.d,$(YALE_PYBRIDGE_SRC))

YALE_PYBRIDGE_ASM_LIB := $(patsubst %.c,%.s,$(YALE_PYBRIDGE_SRC_LIB))
YALE_PYBRIDGE_ASM := $(patsubst %.c,%.s,$(YALE_PYBRIDGE_SRC))

CFLAGS_YALE_PYBRIDGE := -I$(DIRYALE_TEST) -I$(DIRYALE_RUNTIME)

MAKEFILES_YALE_PYBRIDGE := $(DIRYALE_PYBRIDGE)/module.mk
LIBS_YALE_PYBRIDGE := $(DIRYALE_TEST)/libtest.a

.PHONY: YALE_PYBRIDGE clean_YALE_PYBRIDGE distclean_YALE_PYBRIDGE unit_YALE_PYBRIDGE $(LCYALE_PYBRIDGE) clean_$(LCYALE_PYBRIDGE) distclean_$(LCYALE_PYBRIDGE) unit_$(LCYALE_PYBRIDGE)

$(LCYALE_PYBRIDGE): YALE_PYBRIDGE
clean_$(LCYALE_PYBRIDGE): clean_YALE_PYBRIDGE
distclean_$(LCYALE_PYBRIDGE): distclean_YALE_PYBRIDGE
unit_$(LCYALE_PYBRIDGE): unit_YALE_PYBRIDGE

YALE_PYBRIDGE: $(DIRYALE_PYBRIDGE)/libpybridge.a

ifeq ($(WITH_PYTHON),yes)
YALE_PYBRIDGE: $(DIRYALE_PYBRIDGE)/httpparser.so
endif

unit_YALE_PYBRIDGE: $(MAKEFILES_COMMON) $(MAKEFILES_YALE_PYBRIDGE)
	@true

$(DIRYALE_PYBRIDGE)/httpparser.so: $(DIRYALE_PYBRIDGE)/httpcpy.o $(YALE_PYBRIDGE_OBJ_LIB) $(LIBS_YALE_PYBRIDGE) $(MAKEFILES_COMMON) $(MAKEFILES_YALE_PYBRIDGE)
	$(CC) $(CFLAGS) -shared -o $@ $(filter %.o,$^) $(filter %.a,$^)

$(DIRYALE_PYBRIDGE)/libpybridge.a: $(YALE_PYBRIDGE_OBJ_LIB) $(MAKEFILES_COMMON) $(MAKEFILES_YALE_PYBRIDGE)
	rm -f $@
	ar rvs $@ $(filter %.o,$^)

$(DIRYALE_PYBRIDGE)/httpcpy.d: $(DIRYALE_TEST)/httppycparser.h
$(DIRYALE_PYBRIDGE)/httpcpy.o: $(DIRYALE_TEST)/httppycparser.h

$(YALE_PYBRIDGE_OBJ): %.o: %.c %.d $(MAKEFILES_COMMON) $(MAKEFILES_YALE_PYBRIDGE)
	$(CC) $(CFLAGS) -c -o $*.o $*.c $(CFLAGS_YALE_PYBRIDGE)
	$(CC) $(CFLAGS) -c -S -o $*.s $*.c $(CFLAGS_YALE_PYBRIDGE)

$(YALE_PYBRIDGE_DEP): %.d: %.c $(MAKEFILES_COMMON) $(MAKEFILES_YALE_PYBRIDGE)
	$(CC) $(CFLAGS) -MM -MP -MT "$*.d $*.o" -o $*.d $*.c $(CFLAGS_YALE_PYBRIDGE)

clean_YALE_PYBRIDGE:
	rm -f $(YALE_PYBRIDGE_OBJ) $(YALE_PYBRIDGE_DEP) $(YALE_PYBRIDGE_ASM)

distclean_YALE_PYBRIDGE: clean_YALE_PYBRIDGE
	rm -f $(DIRYALE_PYBRIDGE)/libpybridge.a

-include $(DIRYALE_PYBRIDGE)/*.d
